/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bordroproject;

import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author Pc
 */
public class CıkartFrame extends javax.swing.JFrame {

    /**
     * Creates new form CıkartFrame
     */
    ArrayList<Personel> cıkartArray;
    DefaultListModel dlm = new DefaultListModel();
    public CıkartFrame(ArrayList a) {
        initComponents();
        labelUyarı.setVisible(false);
        cıkartArray = a;
        cıkarılcakList.setModel(dlm);
    }
    public CıkartFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cıkarılcakList = new javax.swing.JList<>();
        cıkartButon = new javax.swing.JButton();
        labelUyarı = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setText("Çıkarılacak Personeli Seçiniz :");

        jScrollPane1.setViewportView(cıkarılcakList);

        cıkartButon.setText("İşten Çıkart");
        cıkartButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cıkartButonActionPerformed(evt);
            }
        });

        labelUyarı.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelUyarı.setText("Personeli Seçiniz ! ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cıkartButon)
                        .addGap(284, 284, 284))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelUyarı)
                        .addGap(260, 260, 260))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(cıkartButon)
                .addGap(18, 18, 18)
                .addComponent(labelUyarı)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        dlm.removeAllElements();
        for (int i = 0; i < cıkartArray.size(); i++) {
            boolean ekle = true;
            for (int j = 0; j < dlm.getSize(); j++) {
                if (((String) dlm.get(j)).contains(cıkartArray.get(i).getTür() + "  " + cıkartArray.get(i).getAdi() + "  "
                        + cıkartArray.get(i).getSoyAdi() + "  " + "T.C Kimlik No :" + cıkartArray.get(i).getTcNo())) {
                    ekle = false;
                }
            }
            if (ekle) {
                if (cıkartArray.get(i).getAdi().equalsIgnoreCase("admin")) {
                    continue;
                } else {
                    dlm.addElement(cıkartArray.get(i).getTür() + "  " + cıkartArray.get(i).getAdi() + "  " 
                            + cıkartArray.get(i).getSoyAdi() + "  " + "T.C Kimlik No :" + cıkartArray.get(i).getTcNo() +
                            "  "+cıkartArray.get(i).getMedeniHali()
                            + "  Çocuk Sayısı :" + cıkartArray.get(i).getCocukSayısı() + "  Maaş :" +
                            cıkartArray.get(i).getBrütMaas());
                }
            }
        }
    }//GEN-LAST:event_formWindowActivated

    private void cıkartButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cıkartButonActionPerformed
        // TODO add your handling code here:
        labelUyarı.setVisible(false);

        for (int i = 0; i < cıkartArray.size(); i++) {
            try {
                if (cıkarılcakList.getSelectedValue().contains(cıkartArray.get(i).getTür() + "  " + cıkartArray.get(i).getAdi() + "  " 
                            + cıkartArray.get(i).getSoyAdi() + "  " + "T.C Kimlik No :" + cıkartArray.get(i).getTcNo())) {
                    cıkartArray.remove(i);
                    dlm.removeElementAt(cıkarılcakList.getSelectedIndex());
                }
            } catch (NullPointerException e) {
                labelUyarı.setVisible(true);
                labelUyarı.setText("Listeden Seçim Yapınız.");
            }
        }
    }//GEN-LAST:event_cıkartButonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CıkartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CıkartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CıkartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CıkartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CıkartFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cıkartButon;
    private javax.swing.JList<String> cıkarılcakList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelUyarı;
    // End of variables declaration//GEN-END:variables
}
