package bordroproject;

import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.table.DefaultTableModel;

public class YönetimFrame extends javax.swing.JFrame {

    ArrayList<Personel> yönetimArray;
    DefaultTableModel dtm = new DefaultTableModel();

    public YönetimFrame(ArrayList array) {
        initComponents();
        yönetimArray = array;
        dtm.setColumnCount(5);
        dtm.setColumnIdentifiers(new String[]{"Adı", "Soyadı", "Personel Türü", "Medeni Hali", "Maaş", "Giriş Tarihi"});
        jTable1.setEnabled(false);
        jTable1.setModel(dtm);
        temelUyarı.setVisible(false);
        uyarıAdı.setVisible(false);
        uyarıMaas.setVisible(false);
        uyarıMedeni.setVisible(false);
        uyarıPersonel.setVisible(false);
        uyarıSoyAdı.setVisible(false);
        uyarıTarih.setVisible(false);
        uyarıTc.setVisible(false);
        uyarıDogum.setVisible(false);
        uyarıDiger.setVisible(false);
        this.setLocationRelativeTo(null);
    }

    public YönetimFrame() {
        initComponents();

    }

    boolean desenKontrol(String desenMetni, String icindeDesenArananMetin) {

        Pattern desen = Pattern.compile(desenMetni);
        Matcher arama = desen.matcher(icindeDesenArananMetin);
        return arama.find();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        personelOlustur = new javax.swing.JButton();
        düzenleButon = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        adiTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        soyAdiTxt = new javax.swing.JTextField();
        personelCıkart = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tcNoText = new javax.swing.JTextField();
        asgariButon = new javax.swing.JRadioButton();
        digerButon = new javax.swing.JRadioButton();
        digerUcret = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tarihText = new javax.swing.JTextField();
        checkEvli = new javax.swing.JCheckBox();
        checkBekar = new javax.swing.JCheckBox();
        temizleButon = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        personelButon = new javax.swing.JRadioButton();
        memurButon = new javax.swing.JRadioButton();
        isciButon = new javax.swing.JRadioButton();
        yöneticiButon = new javax.swing.JRadioButton();
        uyarıAdı = new javax.swing.JLabel();
        uyarıSoyAdı = new javax.swing.JLabel();
        uyarıTc = new javax.swing.JLabel();
        uyarıTarih = new javax.swing.JLabel();
        medeniHaliLabel = new javax.swing.JLabel();
        uyarıMedeni = new javax.swing.JLabel();
        uyarıPersonel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        uyarıMaas = new javax.swing.JLabel();
        temelUyarı = new javax.swing.JLabel();
        uyarıDiger = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tarihDogum = new javax.swing.JTextField();
        uyarıDogum = new javax.swing.JLabel();
        cocukSayıCombo = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();

        personelOlustur.setText("Yeni Personel");
        personelOlustur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personelOlusturActionPerformed(evt);
            }
        });

        düzenleButon.setText("Personel Düzenle");
        düzenleButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                düzenleButonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Eklenen Personeller :");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        adiTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adiTxtActionPerformed(evt);
            }
        });

        jLabel2.setText("Adı :");

        jLabel3.setText("Soyadı :");

        soyAdiTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soyAdiTxtActionPerformed(evt);
            }
        });

        personelCıkart.setText("Personel Çıkar");
        personelCıkart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personelCıkartActionPerformed(evt);
            }
        });

        jLabel5.setText("T.C Kimlik No:");

        tcNoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcNoTextActionPerformed(evt);
            }
        });

        buttonGroup1.add(asgariButon);
        asgariButon.setText("Asgari");
        asgariButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asgariButonActionPerformed(evt);
            }
        });

        buttonGroup1.add(digerButon);
        digerButon.setText("Diger");
        digerButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                digerButonActionPerformed(evt);
            }
        });

        digerUcret.setEditable(false);
        digerUcret.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                digerUcretActionPerformed(evt);
            }
        });

        jLabel4.setText("Giriş Tarihi :");

        tarihText.setText("GG/AA/YYYY");
        tarihText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tarihTextMouseClicked(evt);
            }
        });
        tarihText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarihTextActionPerformed(evt);
            }
        });

        buttonGroup3.add(checkEvli);
        checkEvli.setText("Evli");
        checkEvli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkEvliActionPerformed(evt);
            }
        });

        buttonGroup3.add(checkBekar);
        checkBekar.setText("Bekar");
        checkBekar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBekarActionPerformed(evt);
            }
        });

        temizleButon.setText("Seçenekleri Sıfırla");
        temizleButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temizleButonActionPerformed(evt);
            }
        });

        jLabel6.setText("Personel Türü : ");

        buttonGroup2.add(personelButon);
        personelButon.setText("Personel");

        buttonGroup2.add(memurButon);
        memurButon.setText("Memur");

        buttonGroup2.add(isciButon);
        isciButon.setText("Isci");

        buttonGroup2.add(yöneticiButon);
        yöneticiButon.setText("Yönetici");

        uyarıAdı.setText("*");

        uyarıSoyAdı.setText("*");

        uyarıTc.setText("*");

        uyarıTarih.setText("*");

        medeniHaliLabel.setText("Medeni Hali :");

        uyarıMedeni.setText("*");

        uyarıPersonel.setText("*");

        jLabel11.setText("Maas :");

        uyarıMaas.setText("*");

        temelUyarı.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        temelUyarı.setText("* Alanı Düzgün Sekilde Doldurduğunuzdan Emin Olun.");

        uyarıDiger.setText("*");

        jLabel7.setText("Doğum Tarihi :");

        tarihDogum.setText("GG/AA/YYYY");
        tarihDogum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tarihDogumMouseClicked(evt);
            }
        });
        tarihDogum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarihDogumActionPerformed(evt);
            }
        });

        uyarıDogum.setText("*");

        cocukSayıCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));

        jLabel9.setText("Çocuk Sayısı :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(uyarıPersonel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(uyarıMaas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(soyAdiTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(uyarıSoyAdı, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(370, 382, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tcNoText, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(uyarıTc)
                                .addGap(45, 45, 45)
                                .addComponent(uyarıMedeni, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(medeniHaliLabel)
                                .addGap(0, 255, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(adiTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(uyarıAdı)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(tarihText, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(uyarıTarih))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(160, 160, 160)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tarihDogum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(uyarıDogum)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cocukSayıCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(isciButon)
                                    .addComponent(personelButon))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(memurButon)
                                    .addComponent(yöneticiButon)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(28, 28, 28)
                                .addComponent(asgariButon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(digerButon)
                                .addGap(18, 18, 18)
                                .addComponent(digerUcret, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(uyarıDiger)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(checkEvli)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(checkBekar)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(temizleButon, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(personelOlustur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(düzenleButon, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
                    .addComponent(personelCıkart, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addComponent(temelUyarı)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(tarihText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(uyarıTarih)
                                    .addComponent(jLabel9)
                                    .addComponent(cocukSayıCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(adiTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2)
                                .addComponent(uyarıAdı)))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(soyAdiTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(uyarıSoyAdı)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(tarihDogum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(uyarıDogum)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tcNoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(uyarıTc)
                            .addComponent(medeniHaliLabel)
                            .addComponent(uyarıMedeni))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkEvli)
                            .addComponent(checkBekar))
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(personelOlustur, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(temizleButon, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(düzenleButon, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(personelButon)
                    .addComponent(memurButon)
                    .addComponent(uyarıPersonel)
                    .addComponent(personelCıkart, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(yöneticiButon)
                    .addComponent(isciButon))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(uyarıMaas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(asgariButon)
                            .addComponent(digerButon)
                            .addComponent(digerUcret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(uyarıDiger))
                        .addGap(18, 18, 18)
                        .addComponent(temelUyarı)
                        .addGap(18, 18, 18)))
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adiTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adiTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adiTxtActionPerformed

    private void soyAdiTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soyAdiTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soyAdiTxtActionPerformed

    private void tcNoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcNoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tcNoTextActionPerformed

    private void düzenleButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_düzenleButonActionPerformed
        // TODO add your handling code here:
        Düzenle düzenle = new Düzenle(yönetimArray);
        düzenle.setVisible(true);
    }//GEN-LAST:event_düzenleButonActionPerformed

    private void personelCıkartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personelCıkartActionPerformed
        // TODO add your handling code here:
        CıkartFrame cıkart = new CıkartFrame(yönetimArray);
        cıkart.setVisible(true);
    }//GEN-LAST:event_personelCıkartActionPerformed

    private void digerButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_digerButonActionPerformed
        // TODO add your handling code here:
        if (digerButon.isSelected()) {
            digerUcret.setEditable(true);
        }
    }//GEN-LAST:event_digerButonActionPerformed

    private void asgariButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asgariButonActionPerformed
        // TODO add your handling code here:
        if (asgariButon.isSelected()) {
            digerUcret.setText("");
            digerUcret.setEditable(false);

        }
    }//GEN-LAST:event_asgariButonActionPerformed

    private void tarihTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarihTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tarihTextActionPerformed

    private void tarihTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tarihTextMouseClicked
        // TODO add your handling code here:
        tarihText.setText("");
    }//GEN-LAST:event_tarihTextMouseClicked

    private void checkEvliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkEvliActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_checkEvliActionPerformed

    private void checkBekarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBekarActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_checkBekarActionPerformed

    private void personelOlusturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personelOlusturActionPerformed
        boolean olustur = true;
        String[] girisTarih = tarihText.getText().split("/");
        String[] dogumTarih = tarihDogum.getText().split("/");

        if (desenKontrol("[^A-Za-z\\s]", adiTxt.getText()) || (adiTxt.getText().equalsIgnoreCase(""))) {
            uyarıAdı.setVisible(true);
            olustur = false;
        } else {
            uyarıAdı.setVisible(false);

        }
        if (desenKontrol("[^A-Za-z\\s]", soyAdiTxt.getText()) || (soyAdiTxt.getText().equalsIgnoreCase(""))) {
            uyarıSoyAdı.setVisible(true);
            olustur = false;
        } else {
            uyarıSoyAdı.setVisible(false);

        }
        if (!desenKontrol("^[1-9]{1}[0-9]{10}$", tcNoText.getText())) {
            uyarıTc.setVisible(true);
            olustur = false;
        } else {
            uyarıTc.setVisible(false);

        }
        if (!desenKontrol("^([0-2][0-9]||3[0-1])/(0[0-9]||1[0-2])/([0-9][0-9])?[0-9][0-9]$", tarihText.getText()) || girisTarih.length < 3) {
            uyarıTarih.setVisible(true);
            olustur = false;
        } else {
            uyarıTarih.setVisible(false);

        }
        if (!(checkEvli.isSelected() || checkBekar.isSelected())) {
            uyarıMedeni.setVisible(true);
            olustur = false;
        } else {
            uyarıMedeni.setVisible(false);

        }
        if (!((personelButon.isSelected() || isciButon.isSelected()) || (memurButon.isSelected() || yöneticiButon.isSelected()))) {
            uyarıPersonel.setVisible(true);
            olustur = false;
        } else {
            uyarıPersonel.setVisible(false);

        }
        if (!(asgariButon.isSelected() || digerButon.isSelected())) {
            uyarıMaas.setVisible(true);
            olustur = false;
        } else {
            uyarıMaas.setVisible(false);
        }
        if (!desenKontrol("^([0-2][0-9]||3[0-1])/(0[0-9]||1[0-2])/([0-9][0-9])?[0-9][0-9]$", tarihDogum.getText())
                || dogumTarih.length < 3) {
            uyarıDogum.setVisible(true);
            olustur = false;
        } else {
            uyarıDogum.setVisible(false);

        }
        if (olustur) {
            if ((((Integer.parseInt(girisTarih[2]) - Integer.parseInt(dogumTarih[2])) < 18)
                    || (Integer.parseInt(girisTarih[2]) - Integer.parseInt(dogumTarih[2])) > 65)) {
                uyarıTarih.setVisible(true);
                uyarıDogum.setVisible(true);
                olustur = false;
            } else {
                uyarıTarih.setVisible(false);
                uyarıDogum.setVisible(false);
            }
        }
        if (digerButon.isSelected()) {
            if (desenKontrol("[^0-9]", digerUcret.getText()) || digerUcret.getText().equalsIgnoreCase("")) {
                uyarıDiger.setVisible(true);
                olustur = false;

            } else {
                uyarıDiger.setVisible(false);
            }
        }
        for (int i = 0; i < yönetimArray.size(); i++) {
            if (tcNoText.getText().equalsIgnoreCase(yönetimArray.get(i).getTcNo())) {
                olustur = false;
                temelUyarı.setText("Personel Zaten Kayıtlı !");
                temelUyarı.setVisible(true);
                break;
            }
        }
        temelUyarı.setVisible(!olustur);
        if (olustur) {
            SskKaynak kaynak = new SskKaynak();
            String medeniHal = "";
            double maas = kaynak.getAsgariUcret_Ssk();

            if (checkEvli.isSelected()) {
                medeniHal = "Evli";
            } else if (checkBekar.isSelected()) {
                medeniHal = "Bekar";
            }
            if (digerButon.isSelected()) {
                if (Double.parseDouble(digerUcret.getText()) > 2500d) {
                    maas = Double.parseDouble(digerUcret.getText());
                }
            }
            Personel p = null;
            if (personelButon.isSelected()) {
                p = new Personel(adiTxt.getText(), soyAdiTxt.getText(), medeniHal, tcNoText.getText(),
                        tarihText.getText(), tarihDogum.getText(), maas, Integer.parseInt((String) cocukSayıCombo.getSelectedItem()));
                p.setTür("Personel");
            } else if (isciButon.isSelected()) {
                p = new Isci(adiTxt.getText(), soyAdiTxt.getText(), medeniHal, tcNoText.getText(),
                        tarihText.getText(), tarihDogum.getText(), maas, Integer.parseInt((String) cocukSayıCombo.getSelectedItem()));
                p.setTür("Isci");
            } else if (yöneticiButon.isSelected()) {
                p = new Yönetici(adiTxt.getText(), soyAdiTxt.getText(), medeniHal, tcNoText.getText(),
                        tarihText.getText(), tarihDogum.getText(), maas, Integer.parseInt((String) cocukSayıCombo.getSelectedItem()));
                p.setTür("Yönetici");
            } else if (memurButon.isSelected()) {
                p = new Memur(adiTxt.getText(), soyAdiTxt.getText(), medeniHal, tcNoText.getText(),
                        tarihText.getText(), tarihDogum.getText(), maas, Integer.parseInt((String) cocukSayıCombo.getSelectedItem()));
                p.setTür("Memur");
            }
            yönetimArray.add(p);
            dtm.addRow(new String[]{p.getAdi(), p.getSoyAdi(), p.getTür(), p.getMedeniHali(), String.valueOf(p.getBrütMaas()), p.getTarihGiris()});
        }
    }//GEN-LAST:event_personelOlusturActionPerformed

    private void temizleButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temizleButonActionPerformed
        adiTxt.setText("");
        soyAdiTxt.setText("");
        tcNoText.setText("");
        digerUcret.setText("");
        tarihText.setText("GG.AA.YYYY");
        tarihDogum.setText("");
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
        buttonGroup3.clearSelection();
        checkEvli.setSelected(false);
        checkBekar.setSelected(false);
    }//GEN-LAST:event_temizleButonActionPerformed

    private void digerUcretActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_digerUcretActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_digerUcretActionPerformed

    private void tarihDogumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarihDogumActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_tarihDogumActionPerformed

    private void tarihDogumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tarihDogumMouseClicked
        // TODO add your handling code here:
        tarihDogum.setText("");
    }//GEN-LAST:event_tarihDogumMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YönetimFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YönetimFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YönetimFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YönetimFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new YönetimFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adiTxt;
    private javax.swing.JRadioButton asgariButon;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JCheckBox checkBekar;
    private javax.swing.JCheckBox checkEvli;
    private javax.swing.JComboBox<String> cocukSayıCombo;
    private javax.swing.JRadioButton digerButon;
    private javax.swing.JTextField digerUcret;
    private javax.swing.JButton düzenleButon;
    private javax.swing.JRadioButton isciButon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel medeniHaliLabel;
    private javax.swing.JRadioButton memurButon;
    private javax.swing.JRadioButton personelButon;
    private javax.swing.JButton personelCıkart;
    private javax.swing.JButton personelOlustur;
    private javax.swing.JTextField soyAdiTxt;
    private javax.swing.JTextField tarihDogum;
    private javax.swing.JTextField tarihText;
    private javax.swing.JTextField tcNoText;
    private javax.swing.JLabel temelUyarı;
    private javax.swing.JButton temizleButon;
    private javax.swing.JLabel uyarıAdı;
    private javax.swing.JLabel uyarıDiger;
    private javax.swing.JLabel uyarıDogum;
    private javax.swing.JLabel uyarıMaas;
    private javax.swing.JLabel uyarıMedeni;
    private javax.swing.JLabel uyarıPersonel;
    private javax.swing.JLabel uyarıSoyAdı;
    private javax.swing.JLabel uyarıTarih;
    private javax.swing.JLabel uyarıTc;
    private javax.swing.JRadioButton yöneticiButon;
    // End of variables declaration//GEN-END:variables
}
